# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master





stages:
- stage: Alpha
  jobs:

# Extract files
# Extract a variety of archive and compression files such as .7z, .rar, .tar.gz, and .zip
  - job: A
    pool:
      vmImage: 'windows-latest'

    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'filePath'
        filePath: $(System.DefaultWorkingDirectory)\test2.ps1
        arguments: > # Use this to avoid newline characters in multiline string
          -input1 "Hello"
          -input2 "World"
          displayName: 'Print Hello World'
          script: 7z.exe x -aoa -y "D:\a\1\s\Kobayashi_Maru\Content.zip" -o"D:\a\1\s\Kobayashi_Maru\"